apiVersion: v1
kind: Service
metadata:
  name: {{ include "protonpass-server.fullname" . }}
  labels:
    {{- include "protonpass-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
  selector:
    {{- include "protonpass-server.selectorLabels" . | nindent 4 }}
